services:
  nextjs-app:
    build: .
    ports:
      - "3000:3000"
    networks:
      - crud-network
  db:
    env_file: .env
    image: postgres
    ports:
      - "${DB_PORT}:5432"
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - crud-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
networks:
  crud-network:
    driver: bridge
volumes:
  postgres_data:
