services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./prisma:/app/prisma
      - ./node_modules/.prisma:/app/node_modules/.prisma
    networks:
      - lkmx-network
    entrypoint: ["sh", "-c", "npx prisma migrate deploy && npm run dev"]
    depends_on:
      - db
  db:
    env_file: .env
    image: postgres
    ports:
      - "${DB_PORT}:5432"
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - lkmx-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  lkmx-network:
    driver: bridge
volumes:
  postgres_data:
